### ISSUE TITLE
Markbot is not accepting my css code

### ISSUE THREAD

**Issue by skhan9179** [skhan9179/horizontal-nav#1]
Markbot keeps giving me an error **(Expected to see font-family with a different value inside h1 {})** for typing the incorrect font family for the h1 tag. However, I followed the instructions and used `font-family: Bevan, sans-serif` but it wouldn't accept that code. 
I even tried `font-family: Bevan, cursive` which was the css code I pulled from Google fonts but that didn't work either.

https://github.com/skhan9179/horizontal-nav/blob/gh-pages/css/main.css#L31

@thomasjbradley

**Comment by thomasjbradley** [comment]
That’s because `Bevan` isn’t a `sans-serif` font, it’s a `serif` font, try this: `font-family: Bevan, serif`;

**Comment by skhan9179** [comment]
Thanks, that worked!
